version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build: ./Docker/php
    volumes:
      - ./www/html:/var/www/html
      - ./Docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db

  db:
    image: mysql:8.0.20
    ports:
      - 13306:3306
    volumes:
      - ./Docker/init/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db